import type { Metadata } from "next";
import { Figtree, Lexend } from "next/font/google";

import "./globals.css";

// Import font Bungee
const figtree = Figtree({
  variable: "--font-figtree", // Variabel CSS
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend", // Variabel CSS
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${lexend.variable} antialiased`} style={{ backgroundColor: "#222222", }}>
        {children}
      </body>
    </html>
  );
}
